### ISSUE TITLE
Shaping issue with  ที่ and ที้ 

### ISSUE THREAD

**Issue by davelab6** [cadsondemak/trirong#4]
A user wrote to GF:

> some letters which has an "accent/top vowels" has the symbol overlapped when typing. The letters in questions are ที่ and ที้ - the top vowels overlap with the สระ อี, making it not readable. We are wondering if this might be an issue with Adobe software? Would you be able to suggest a solution for this issue?

**Comment by suppakit-** [comment]
The solution is to enable Adobe World-Ready to fix the problem. :D
